[Service]
Type=simple
User=turnserver
Group=turnserver
ExecStart=
ExecStart=/usr/bin/turnserver -c /etc/verdant/turnserver.conf --pidfile=/run/coturn/turnserver.pid
RuntimeDirectory=coturn
Restart=on-failure
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true
ProtectHome=true
ProtectSystem=strict
ReadWritePaths=/run/coturn
StandardOutput=journal
StandardError=journal
